// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhO_lg9NAkEj1sUy3PtP7-rit3Vp85a4',
    appId: '1:786519830595:web:fcb62eaabcc8e6168c24f6',
    messagingSenderId: '786519830595',
    projectId: 'lusoamerican-c84fd',
    authDomain: 'lusoamerican-c84fd.firebaseapp.com',
    storageBucket: 'lusoamerican-c84fd.appspot.com',
    measurementId: 'G-021QEBJB1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0nlm3TTSLo4smbmMwHVlaV0gDrKKS4I',
    appId: '1:786519830595:android:820dd2acc97c39008c24f6',
    messagingSenderId: '786519830595',
    projectId: 'lusoamerican-c84fd',
    storageBucket: 'lusoamerican-c84fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0YNGkhakWpW5ljNY3CrB930Ed2vfP3k',
    appId: '1:786519830595:ios:0cb128cf3e985d598c24f6',
    messagingSenderId: '786519830595',
    projectId: 'lusoamerican-c84fd',
    storageBucket: 'lusoamerican-c84fd.appspot.com',
    iosClientId: '786519830595-adugfssd5249amq4f8d1olccpasee3cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lusoAmericanFinancial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0YNGkhakWpW5ljNY3CrB930Ed2vfP3k',
    appId: '1:786519830595:ios:0cb128cf3e985d598c24f6',
    messagingSenderId: '786519830595',
    projectId: 'lusoamerican-c84fd',
    storageBucket: 'lusoamerican-c84fd.appspot.com',
    iosClientId: '786519830595-adugfssd5249amq4f8d1olccpasee3cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lusoAmericanFinancial',
  );
}
